### ISSUE TITLE
Google Play returned error

### ISSUE THREAD

**Issue by bsz0206** [GoogleCloudPlatform/recaptcha-enterprise-flutter#12]
Google Play returns the following on 18.2.1:

Upgrade to a newer com.google.android.recaptcha SDK version
Jul 1, 2023 02:55
The SDK developer com.google.android.recaptcha has added a note for recaptcha:18.2.0. Here's what the SDK developer told us:

Version 18.2.0 should not be used in production, because it might make your app non-functional due to some internal errors. To avoid these problems, migrate directly to Android SDK 18.2.1 or later. For details, see the issue report on GitHub: https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/52

If you do not upgrade to a newer version, you may not be able to release future versions of your app with this SDK.

**Comment by mcorner** [comment]
Odd Are you sure you are using 18.2.1 from pub.dev?  The source clearly points at 18.2.1.

**Comment by bsz0206** [comment]
yes, I checked that too. This is odd but I rebuilt and didn't get it.
