### ISSUE TITLE
Action value missing from assessment when token is generated from iOS

### ISSUE THREAD

**Issue by gabrielginter** [GoogleCloudPlatform/recaptcha-enterprise-flutter#18]
My code calls `execute` with the default action like:

`var token = await RecaptchaEnterprise.execute(RecaptchaAction.LOGIN());` (`initClient` is called earlier successfully)

When getting the assessment on my server for such token, the `tokenProperties.action` value in the returned JSON is blank. This does not happen on tokens generated on Android.

Is this expected behaviour?

Thanks

**Comment by mcorner** [comment]
You are correct, fix in progress.  Thanks for the report

**Comment by mcorner** [comment]
Ok, pushed to pub.dev as 18.2.2+1.  Give it a try and LMK if there are issues.
