### ISSUE TITLE
Got Play store note

### ISSUE THREAD

**Issue by abhinavsinghring** [GoogleCloudPlatform/recaptcha-enterprise-flutter#28]
In my flutter app I'm getting this error in Play Store even though I haven't added this plugin in pubspec.yaml

The SDK provider of com.google.android.recaptcha:recaptcha has added a note for recaptcha:18.1.2. Here's what the SDK provider told us:

A critical security vulnerability was discovered in reCAPTCHA Enterprise for Mobile. The vulnerability has been patched in the latest SDK release. Customers will need to update their Android application with the reCAPTCHA Enterprise for Mobile SDK, version 18.4.0 or above. We strongly recommend you update to the latest version as soon as possible.

How can I fix this.

**Comment by mcorner** [comment]
Are you using firebase auth perhaps?

**Comment by abhinavsinghring** [comment]
yes

**Comment by mcorner** [comment]
We will update this here: https://github.com/firebase/firebase-android-sdk/issues/5638
