### ISSUE TITLE
Package name not allowed Error

### ISSUE THREAD

**Issue by MojtabaMohammadzadeh** [GoogleCloudPlatform/recaptcha-enterprise-flutter#30]
I used this package in my Flutter App and I got this error 
FL_INIT_FAILED Message com.google.android.recaptcha.RecaptchaException: Package name not allowed
also I run example of packege and I get this error again 
please help me how can I solve it

**Comment by walterjgsp** [comment]
What's the version of the SDK that's being used?

**Comment by rafaeldecker** [comment]
I had the same issue here. Using the lib version `18.4.0`. I'm updating library version to `18.4.1` to check if it has been fixed.
Exception:
```
PlatformException(FL_INIT_FAILED, com.google.android.recaptcha.RecaptchaException: Internal Error, null, null)
```
Issue has happened on android:
Model: Motorola moto g(50) 5G (android 12)

**Comment by mcorner** [comment]
@rafaeldecker That is not the same exception as OP: "Package name not allowed".  Please open a new issue.

**Comment by rafaeldecker** [comment]
> @rafaeldecker That is not the same exception as OP: "Package name not allowed". Please open a new issue.

You are right, sorry for that. 
I'll check if it is still happening on version `18.4.1` before opening a new issue. 

Thanks

**Comment by mcorner** [comment]
18.4.2 wil be out shortly and fixes a background crash, so you should probably wait (it is already out in the non flutter version)

We have some great improvements working through our beta releases in the non flutter version. We were not planning on bringing the betas to flutter and react native, but lmk if that is of interest.

**Comment by tronghau2110** [comment]
How about fix it ?

**Comment by mcorner** [comment]
I am assuming that the package name was updated and fixed the issue.  Please reopen if that is not the case.

**Comment by jalal-zy** [comment]
Same here. Any solution?
version recaptcha_enterprise_flutter: ^18.5.1

**Comment by walterjgsp** [comment]
@jalal-zy In what platform are you seeing this? Android or iOS? 

Please confirm if the package that you defined is correct for the site key that you're sending. Since flutter support both Android and iOS it is possible that the site key you're sending to the specific platform is actually incorrect.

**Comment by mackymangampo** [comment]
Hi I am working with recaptcha and encounter this error after I've create an android site key. 

Version: recaptcha_enterprise_flutter: ^18.7.0

![Image](https://github.com/user-attachments/assets/19fe5fad-b9ec-4164-bd3a-dfc3a55194b0)

**Comment by walterjgsp** [comment]
@mackymangampo, this is the same problem that @jalal-zy should be facing. What platform are you seeing this? Android or iOS? 

The package names are case sensitive so please make sure that the package you defined is correct for the site key that you're using.
