### ISSUE TITLE
Recaptcha initialize error on iOS and Android (Flutter)

### ISSUE THREAD

**Issue by hasanilyas185** [GoogleCloudPlatform/recaptcha-enterprise-flutter#32]
Describe the bug
![Screenshot 2024-02-22 at 12 52 27 PM](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-flutter/assets/44157654/2debdac5-defe-4a20-abc6-8268142ba109)
![Screenshot 2024-02-22 at 12 51 32 PM](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-flutter/assets/44157654/8c570c98-5bb2-48eb-b748-0a505a843116)

getting multiple crashes for these errors on both android and iOS have tried retry logic but still didnt work

reCAPTCHA Site Key

Please include your site key so we can examine backend metrics for your integration.

Integration Method

Flutter pub cache dependency

SDK Version (e.g. 18.0.1):
18.4.0

To Reproduce

cannot reproduce on our development environment but we can see 422 crash in 2 days on firebase crashlytics

We cannot reproduce the issue, during our development and testing.

Expected behavior

Screenshots

Xcode version for iOS (please complete the following information):

Xcode 15.0
Device (please complete the following information):

Model: [e.g. Pixel 7, iPhone6]
OS: [e.g. Android 28, iOS8.1]
Emulator/Simulator or real Device?
Additional context

**Comment by romaCaldeira** [comment]
I have the same problem

**Comment by mcorner** [comment]
Network errors are exactly that: the SDK is unable to contact our server.  We are in the process of adding internal retires to the SDK so you don't have to implement this yourself, but for now the solution is to retry with some exponential backoff until it can connect well enough to initialize.

**Comment by mcorner** [comment]
As mentioned we are working on internal retries to make this easier, but until then you will need to call the API when there is a network or retry.
