### ISSUE TITLE
18.5.1 build error

### ISSUE THREAD

**Issue by flywithbug** [GoogleCloudPlatform/recaptcha-enterprise-flutter#45]
![img_v3_02bh_1f2ab95c-0298-451f-b6aa-6103162e1b2h](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-flutter/assets/3955387/9679a10f-3099-430b-9ea8-8c0bd223a4ca)

recaptcha_enterprise_flutter:
  dependency: transitive
  description:
    name: recaptcha_enterprise_flutter
    sha256: "2b53a990c686272f4e6d6f614ce7b6d5d4ccd6468ae7300d3b6e0af940852b2e"
    url: "https://pub.flutter-io.cn/"
  source: hosted
  version: "18.5.1"

**Comment by flywithbug** [comment]
after flutter clean  & flutter get 

still not working

**Comment by Mu7ammadRasul** [comment]
if this is what caused the error I would be furious cause I been trying for 3 days now!

**Comment by mcorner** [comment]
There isn't much detail here. There should be more error messages higher up in the output. Is that a GitHub actions build?

What version of xCode are you using?

**Comment by Mu7ammadRasul** [comment]
> There isn't much detail here. There should be more error messages higher up in the output. Is that a GitHub actions build?
> 
> What version of xCode are you using?

here is what I got: `ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_Recaptcha in RecaptchaEnterprise[6](h5A6qS67.swift.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by Mu7ammadRasul** [comment]
> Duplicate of [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#109](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/109)
> 
> Please use xCode 15.3 or greater

I use MacBook Pro 2017, the latest Xcode version I got is 15.2 but I also got the same error from cloud using the latest versions either for Xcod or macOS provided by cloud!

**Comment by mcorner** [comment]
Unfortunately there are changes in xCode (I would expect more) that Apple made to support privacy manifests. So as part of that we had to move our minimum requirement. 

I am 95% sure this is the problem, so please recheck on xcode 15.3 or greater.

**Comment by Mu7ammadRasul** [comment]
> Unfortunately there are changes in xCode (I would expect more) that Apple made to support privacy manifests. So as part of that we had to move our minimum requirement.
> 
> I am 95% sure this is the problem, so please recheck on xcode 15.3 or greater.

I'll keep this in mind and would wait for it for sure, I understand the changes been made were actually more than one and I tried all the given solutions by either Xcode devs or the community, I used the package to overcome an alert where I had it during distributing my flutter app on play store, regarding iOS I was able to release build 3 times before I encounter the error and I also distributed my app to App Store prior to the error, I haven't changes anything in the app so the error was surprising, the cli didn't even gave me the full err description, finally I managed to remove the package in my app just to be error free, if future versions would fix the issue I would definitely re-use the package one again...

**Comment by mcorner** [comment]
@flywithbug I am not sure if this is your problem or not, but please check the XCode version and let us know.

**Comment by s-tyd** [comment]
@mcorner 
I was using github actions to build, but as soon as I added the recaptcha, I couldn't build.
But I set the version to lateste and it built fine, thanks!

```yaml
- uses: actions/checkout@v4
- name: Setup Xcode version
  uses: maxim-lobanov/setup-xcode@v1
  with:
    xcode-version: latest-stable
- name: Display Xcode Version
  run: xcodebuild -version
```
