### ISSUE TITLE
PlatformException(2, Invalid Key Type., null, null)

### ISSUE THREAD

**Issue by jalal-zy** [GoogleCloudPlatform/recaptcha-enterprise-flutter#47]
PlatformException(2, Invalid Key Type., null, null)
on Flutter iOS

**Comment by mcorner** [comment]
You are probably using an Android key on iOS.

**Comment by jalal-zy** [comment]
That is correct. Thank you.

**Comment by khaledmorshed** [comment]
You are probably using an Android key on iOS. Do you indicate bellow snipped code? if it points that, I kept it empty on iosSiteKey. And it gives error what I mentioned.
{
    "androidSiteKey": "6Lf-FA8oAAAAAH+rest_of_the_value",
    "iosSiteKey": ""
}
