### ISSUE TITLE
Kotlin version

### ISSUE THREAD

**Issue by naj147** [GoogleCloudPlatform/recaptcha-enterprise-flutter#49]
Why is the kotlin version set at 1.9.22?
The jetified binary version gives a lot of issues that are only solvable if the Kotlin version is updated in the flutter generated android project, although it doesn't seem that you need such kotlin version? (ex of the issue: The binary version of its metadata is 1.9.0, expected version is 1.7.1)

Kotlin version 1.7.10 is more than enough (fits the newest version on the flutter sdk 3.22.0).

If the idea of having a Kotlin version without justification, then it should be lowered to support as much as possible.
If it's some internal google best practice, then it should be reviewed.

If there is some other justification, then correct me please.

https://mvnrepository.com/artifact/com.google.android.recaptcha/recaptcha/18.5.1 
in mvn, the kotlin stdlib used is 1.7.0, so I still don't get why the Jars have been compiled with a new kotlin version, making it impossible to include this in .aar generated by flutter without hacking it in.

**Comment by walterjgsp** [comment]
@naj147 thanks for opening the issue. Unfortunately this is a Google policy and it's not something that we can solve easily internally. Some work is being done to change that behavior but we don't have an idea of the ETA for it yet. In the meantime the Android SDK for recaptcha follows the most recent versions of Kotlin. Sorry if this is causing you trouble we are working as best as possible to support the maximum versions we can.

**Comment by mcorner** [comment]
We have taken this under advisement and there is some internal work going on to use somewhat older kotlin versions.  Keep an eye out for future releases.
