### ISSUE TITLE
Unable check riskfactor score

### ISSUE THREAD

**Issue by Vidhyasagar731** [GoogleCloudPlatform/recaptcha-enterprise-flutter#51]
I dont know what's the next step to check my device is good score. After called the execute function and retrieved the token.

**Comment by walterjgsp** [comment]
Hi @Vidhyasagar731, after you receive a token please follow the guidance at https://cloud.google.com/recaptcha/docs/create-assessment-mobile to use it in order to get the score

**Comment by Vidhyasagar731** [comment]
Thanks sir @walterjgsp.
