### ISSUE TITLE
Failed to generate reCAPTCHA Token: MissingPluginException

### ISSUE THREAD

**Issue by haninhn** [GoogleCloudPlatform/recaptcha-enterprise-flutter#61]
Failed to generate reCAPTCHA Token: MissingPluginException(No implementation found for method fetchClient on channel recaptcha_enterprise)
I/flutter ( 9752): Failed to fetch reCAPTCHA token: Exception: Failed to generate reCAPTCHA Token: MissingPluginException(No implementation found for method fetchClient on channel recaptcha_enterprise)

**Comment by walterjgsp** [comment]
Hi @haninhn, thanks for opening the issue. What's the version of the recaptcha are you using?

**Comment by walterjgsp** [comment]
Thanks for sharing the code snippet, it will help us investigate. Are you migrating from a previous version of reCAPTCHA?

**Comment by haninhn** [comment]
i  was installed  this  plugin flutter_gcaptcha_v3 2.1.1,   then   i added  this plugin. recaptcha_enterprise_flutter    now i just use recaptcha_enterprise_flutter

**Comment by imota** [comment]
Are these the only files you're importing from recaptcha? The fetchClient method is declared in  `recaptcha_enterprise.dart`

Try including all of the files below and let us know if it solves your problem:

```
import 'package:recaptcha_enterprise_flutter/recaptcha.dart';
import 'package:recaptcha_enterprise_flutter/recaptcha_client.dart';
import 'package:recaptcha_enterprise_flutter/recaptcha_enterprise.dart';
import 'package:recaptcha_enterprise_flutter/recaptcha_action.dart';
```

**Comment by haninhn** [comment]
RecaptchaEnterprise is Deprecated. i fixed this  bug "MissingPluginException"  by adding   like this in yaml ,  i remove the version number :   recaptcha_enterprise_flutter:    
Now i get  another bug :  platformexception(fl_execute_failed, com.google.android.recaptcha.recaptchaexception: key type invalid, null, null)

**Comment by haninhn** [comment]
Failed to fetch reCAPTCHA token: Exception: Failed to generate reCAPTCHA Token: PlatformException(FL_EXECUTE_FAILED, com.google.android.recaptcha.RecaptchaException: Key type invalid, null, null)
D/EGL_emulation( 9106):   why i get this error don't understand

**Comment by walterjgsp** [comment]
This means that the key you're using to initialize the client is incorrect. Either using an Android one in the iOS environment or the other way around.

**Comment by haninhn** [comment]
should i have key for ios and another key for android ?

**Comment by walterjgsp** [comment]
Yes, it's necessary one key per platform. More information about configuring keys can be found at https://cloud.google.com/recaptcha/docs/create-key-mobile
