### ISSUE TITLE
MALFORMED

### ISSUE THREAD

**Issue by haninhn** [GoogleCloudPlatform/recaptcha-enterprise-flutter#62]
"tokenProperties": {
                    "valid": false,
                    "invalidReason": "MALFORMED",
                    "hostname": "",
                    "androidPackageName": "",
                    "iosBundleId": "",
                    "action": "",
                    "createTime": "1970-01-01T00:00:00Z"
                 }

Future<String> fetchRecaptchaToken(RecaptchaAction action) async {
  try {
    debugPrint("Fetching reCAPTCHA Token action ; ${action.action.toString()}");
    String recaptchaKey = dotenv.env['RECAPTCHA_ANDROID_KEY'] ?? "";
    String token = await Recaptcha.fetchClient(recaptchaKey).then((client) => client.execute(action, timeout: 10000));
    debugPrint("Generated reCAPTCHA Token: $token");
    return token;
  } catch (e) {
    debugPrint("Failed to generate reCAPTCHA Token: $e");
    if(e.toString().contains("No network found on device")) {
      throw const SocketException("Please connect to the internet to continue");
    }
    throw Exception("Failed to generate reCAPTCHA Token: $e");
  }
}
   recaptcha_enterprise_flutter:

**Comment by haninhn** [comment]
i create key for android platform,  i generate the token then i test it  in his api. https://recaptchaenterprise.googleapis.com/v1/projects/*****-recaptcha-android/assessments?key=AIzaSyBzlzYsImRU**********4.  {
    "name": "projects/422612428131/assessments/5ba86fe476000000",
    "event": {
        "token": "03AFcWeA5u46y39qqqcYmZ48riysN7fH3u0d95Bwj0rcWPcMi1SXEUOs1ZM74uEGix8y-6E1IDdVH3Wly5Xs8Wy_LYCcK1l7jn-XzetjAsZ8FyYVsiJDLHya7PxSb2Q2_Pz30xCl-Y7OkgA9bYzEQ_fwKjwnUuYI_y-H6WNWG7Q77Mo2qzzFrUKkGd5QT2Ac_Xt8aIK67FiQ3OuiNZt-hs3Wi2Ka4FeuIK6p-JtH4fagM6quQ-RwRaYa9y3B20lJIKItS_bCZzmATuffBengoca--4ZVUg29Sk20VApTa3S_RZ2gXo76Hdt7mBWxKh1N4kYOSSQ1FCzZh5Uj0NPr9OOAvxC3xgUqHh7NVvBKSYQAWR2EnYTFpFlfT7OFwTuiDrP7EosxuK-xtArFDbQFUs-UtN88L7T0adXyl1_gO0LjneFR6fdftZQ3ead9SjP7fZ-XlhecqenfMa0K2LXofkUyocyWB3i5zfBBs5uTPFTEp-lfbLcAMbXctguZT0WwPsQFNKr5fjVukQj2khTCLqXsYMlU-1YV0JnfFM051pp6vQAEeRcQJKqNa2_bHsQ4WbRMLQnxES2doFQkzx27ikvmdUODoGFpF-hTJR26QUbcCTBxlntiNm_dFn6MuALEXQfBFV6xRWRmObtUf_Kcgx1EannwTYaXfgMaoeShrsfgLFsMaSbETAkgVker6Akq2Kbsdvi-e7q4r40NlJqzPvRpcmhCdpIjXfnHF4qD6K6HLB0P3y8NmrvBAphlYf2j_OXoEAlRv53TwZDVeuajpPLVmCSkUls81j9f1Az3dFzWmR8dtMZ7zAj1svpcyp7YVkSSYp4HHdNAXlkW9hr0dDF-jIVVAVZbgCdxqynSVPuTWyiOgqKLaDvFkQ1l1RHM17hPZ4Im1h5hRvAiAG0WiiGioL6gyMz58XIejG_UA3Cd_paTDcizZBFYoY0O34pYDzLO3UK8I4q2gRJO7V8Kj5D-alIOILA9iGsE",
        "siteKey": "6LeSv6kqAAAA****************",
        "userAgent": "",
        "userIpAddress": "",
        "expectedAction": "",
        "hashedAccountId": "",
        "express": false,
        "requestedUri": "",
        "wafTokenAssessment": false,
        "ja3": "",
        "headers": [],
        "firewallPolicyEvaluation": false,
        "fraudPrevention": "FRAUD_PREVENTION_UNSPECIFIED"
    },
    "riskAnalysis": {
        "score": 0,
        "reasons": [],
        "extendedVerdictReasons": [],
        "challenge": "CHALLENGE_UNSPECIFIED"
    },
    "tokenProperties": {
        "valid": false,
        "invalidReason": "MALFORMED",
        "hostname": "",
        "androidPackageName": "",
        "iosBundleId": "",
        "action": "",
        "createTime": "1970-01-01T00:00:00Z"
    }
}

**Comment by haninhn** [comment]
i use just this function  and i copy it from log to test it in the post man 

`Future<String> fetchRecaptchaToken(RecaptchaAction action) async {
  try {
    debugPrint("Fetching reCAPTCHA Token action ; ${action.action.toString()}");
    String recaptchaKey = dotenv.env['RECAPTCHA_ANDROID_KEY'] ?? "";
    debugPrint("Fetching reCAPTCHA Token action ; ${recaptchaKey.toString()}");

    String token = await Recaptcha.fetchClient(recaptchaKey).then((client) => client.execute(RecaptchaAction.custom(""), timeout: 10000));
    debugPrint("Generated reCAPTCHA Token: $token");
    return token;
  } catch (e) {
    debugPrint("Failed to generate reCAPTCHA Token: $e");
    if(e.toString().contains("No network found on device")) {
      throw const SocketException("Please connect to the internet to continue");
    }
    throw Exception("Failed to generate reCAPTCHA Token: $e");
  }
}`



`I/flutter (21359): Generated reCAPTCHA Token: 03AFcWeA4RXHREAgrF3qLx_3-75MxhqMHHiPemoaCedaZwY5MIFTjlaBtoNsE3B3ZG3WemXjTf3oEKOiqfEolU_5yemrXYRv8Jf64FOJkgyy26z_6kfGtVZaJfAyDGan6BphoTgkkGEoL4jyoKWMrm84UUbzbEIuEjls4znZbncIy-CcovHZCnzYh7eauzMTEasNPreMfU-ozb-GpHuZLf_Q8vb2JaEZ_IMBqvT7uzxPvNpssmHx8j9DiqAnTC9A-sHnFwBFBUTrasIP2XqzAkUo-nnMrTDKVfgY1PuOWo426wqqcZ5YyUZuZHVX_4UIVEdnXtNa0HSoY44iHX62gJAbjNHkwW49AnmPkFzM9xY79OwZXlfEDCqISAuZQIWkX4uMZ1KruzuqKhBCToOAnbJJarNeL_xZH0pskOoqTFm0bTvyogOyIavZapCaxKpNYbmQErshuvwkjOzgvKoMyLQFIWdaYeUuRZwYnBa7_7aXHOZh_JC3OqH0i1gQ2VJ8YV9dMK-ikyJN0CDEqZtOBatSCbg21YP8A06EmkXWueNWbH3LbjJ5SM0ItARrHhm_dyLencXhaZinxaIWXXlQNl1QT1S8F-Ng-OZVX80Pfo_H8V5C9O7uxNhmrt_WUav0bghrC-aFHFmrlUidORaol5-55ppmWxlVKw6IOIJeruC1kwHEIrIumLkkxC1LWf0eQTeP7YyYh7yIoDrgdgp_KDvtA8sFWBvBXiq2To4kW_hDbIVGPYssycJE2wYjAs9GPhWCnjynvFL9baBnn9TdLYtdpDJlLvnoMO_VR0KyNufuIeT44T50CmpzKD9rwomhLauhet9EpvhbDOmRNjmbLCdmCm5Gw7RIJgHjO3yqYfkSE0GPOyUuQ1Oom35zGbNpdLFnT2iIBJ3iTSECZPCLZFQh_KiC4GpXaAgrTY3Gg_MeIflumZogCxM6mMaLFQ0hland0Mi4Z4ZWaU4GE0fuQyy2hqOUaSJatuQT`. 




i use  /recaptchaenterprise.googleapis.com. to verifer directly  and is end it in the body. like this. 
{"event": {
    "token": "03AFcWeA4RXHREAgrF3qLx_3-75MxhqMHHiPemoaCedaZwY5MIFTjlaBtoNsE3B3ZG3WemXjTf3oEKOiqfEolU_5yemrXYRv8Jf64FOJkgyy26z_6kfGtVZaJfAyDGan6BphoTgkkGEoL4jyoKWMrm84UUbzbEIuEjls4znZbncIy-CcovHZCnzYh7eauzMTEasNPreMfU-ozb-GpHuZLf_Q8vb2JaEZ_IMBqvT7uzxPvNpssmHx8j9DiqAnTC9A-sHnFwBFBUTrasIP2XqzAkUo-nnMrTDKVfgY1PuOWo426wqqcZ5YyUZuZHVX_4UIVEdnXtNa0HSoY44iHX62gJAbjNHkwW49AnmPkFzM9xY79OwZXlfEDCqISAuZQIWkX4uMZ1KruzuqKhBCToOAnbJJarNeL_xZH0pskOoqTFm0bTvyogOyIavZapCaxKpNYbmQErshuvwkjOzgvKoMyLQFIWdaYeUuRZwYnBa7_7aXHOZh_JC3OqH0i1gQ2VJ8YV9dMK-ikyJN0CDEqZtOBatSCbg21YP8A06EmkXWueNWbH3LbjJ5SM0ItARrHhm_dyLencXhaZinxaIWXXlQNl1QT1S8F-Ng-OZVX80Pfo_H8V5C9O7uxNhmrt_WUav0bghrC-aFHFmrlUidORaol5-55ppmWxlVKw6IOIJeruC1kwHEIrIumLkkxC1LWf0eQTeP7YyYh7yIoDrgdgp_KDvtA8sFWBvBXiq2To4kW_hDbIVGPYssycJE2wYjAs9GPhWCnjynvFL9baBnn9TdLYtdpDJlLvnoMO_VR0KyNufuIeT44T50CmpzKD9rwomhLauhet9EpvhbDOmRNjmbLCdmCm5Gw7RIJgHjO3yqYfkSE0GPOyUuQ1Oom35zGbNpdLFnT2iIBJ3iTSECZPCLZFQh_KiC4GpXaAgrTY3Gg_MeIflumZogCxM6mMaLFQ0hland0Mi4Z4ZWaU4GE0fuQyy2hqOUaSJatuQT",  
  "siteKey": "6LcxQ6kqAAAAAH4l6By7QZcMiKXRvCmgjEnnfg6v"
  }
}

**Comment by walterjgsp** [comment]
This issue was seeing before. Copying directly can strip a part of the token away and not the full token as the string is big and sometimes not fully supported to be shown in the logs. One solution is to put this token into a file or send it to a backend that do the request for you.

**Comment by walterjgsp** [comment]
@haninhn, I assume that using the big token it's working? Closing the bug for now and we can reopen in case it's not working.
