### ISSUE TITLE
Can't use on android off play applications

### ISSUE THREAD

**Issue by 865102930** [GoogleCloudPlatform/recaptcha-enterprise-flutter#9]
I've set the apikey, I can use it and can also get the token on ios but cant init on android. 

[✓] Flutter (Channel unknown, 3.0.0, on macOS 13.3 22E252 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.0 at /Users/btcc/Development/flutter
    • Upstream repository unknown
    • Framework revision ee4e09cce0 (1 year, 1 month ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/btcc/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Users/btcc/Library/Java/JavaVirtualMachines/corretto-11.0.18/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

I/flutter (21185): Caught exception on init: PlatformException(FL_INIT_FAILED, com.google.android.recaptcha.RecaptchaException: Internal Error, null, null)
I/chromium(21185): [INFO:CONSOLE(1)] "Uncaught ReferenceError: recaptcha is not defined", source: https://www.recaptcha.net/recaptcha/api3/mwv (1)

**Comment by mcorner** [comment]
Would you mind posting the code you are using with the SDK?

Does this happen every time you use it?

**Comment by 865102930** [comment]
> Would you mind posting the code you are using with the SDK?
> 
> Does this happen every time you use it?

I use GetX in the app, When I get in the login page and then init Google Recaptcha. 

```
@override
  void onReady() async {
    // TODO: implement onReady

    /// init Google recaptcha
    initClient();

    super.onReady();
}

// step1
void initClient() async {
    try {
      await RecaptchaEnterprise.initClient(Platform.isAndroid ? AppGlobalConfig.captchaKey_android : AppGlobalConfig.captchaKey_ios);
    } on PlatformException catch (err) {
      print('Caught Platform exception on init: code:${err.code}-----msg:${err.message}');
    } catch (error) {
      print('Caught exception on init: $error');
    }
  }

```

I/flutter (20348): Caught Platform exception on init: code:FL_INIT_FAILED-----msg:com.google.android.recaptcha.RecaptchaException: Internal Error
I/chromium(20348): [INFO:CONSOLE(1)] "Uncaught ReferenceError: recaptcha is not defined", source: https://www.recaptcha.net/recaptcha/api3/mwv (1)
E/chromium(20348): [ERROR:aw_browser_terminator.cc(125)] Renderer process (22025) crash detected (code -1).

**Comment by mcorner** [comment]
Thanks for this. Let's see if we can narrow it down more.

This is the interesting line: `E/chromium(20348): [ERROR:aw_browser_terminator.cc(125)] Renderer process (22025) crash detected (code -1).`  It looks like you are running into a Chromium bug, which is pretty odd.

What kind of device/emulator are you running this on?

Can you try running the sample application that is included in the repository on the same device?

Can you try running your app on another device?

**Comment by 865102930** [comment]
> Thanks for this. Let's see if we can narrow it down more.
> 
> This is the interesting line: `E/chromium(20348): [ERROR:aw_browser_terminator.cc(125)] Renderer process (22025) crash detected (code -1).` It looks like you are running into a Chromium bug, which is pretty odd.
> 
> What kind of device/emulator are you running this on?
> 
> Can you try running the sample application that is included in the repository on the same device?
> 
> Can you try running your app on another device?

This error msg show on the device(OPPO A32, Android Version 11, Mode PDVM00)
![IMAGE 2023-06-12 16:25:51](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-flutter/assets/18364926/ebfc5621-08c7-44c4-99f5-22fc269e9e96)

it shows a different error msg on another device(HONOR 70)
```
E/hwschromium-4598(13383): [ERROR:ssl_client_socket_impl.cc(981)] handshake failed; returned -1, SSL error code 1, net_error -202
I/hwschromium-4598(13383): [INFO:aw_ssl_host_state_delegate.cc(287)] QueryPolicy for host: *** cert serial number: 018893909B29 cert subject: misc.google.com cert issuer: Charles Proxy CA (8 三月 2019, 192.168.0.104) cert errorno: -202 this: 0x6a00523100
I/hwschromium-4598(13383): [INFO:aw_ssl_host_state_delegate.cc(301)] QueryPolicy for "***" result is denied
I/hwschromium-4598(13383): [INFO:network_service_network_delegate.cc(246)] final url https//*** error_code -3 ip address: ignored
I/hwbr_engine_a(13383): connectionTypeChanged connectionType = 2, connectionSubType = 0
I/flutter (13383): Caught Platform exception on init: code:FL_INIT_FAILED-----msg:com.google.android.recaptcha.RecaptchaException: Network Error
I/hwbr_engine_a(13383): connectionTypeChanged connectionType = 2, connectionSubType = 0
```

![IMAGE 2023-06-12 16:30:37](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-flutter/assets/18364926/ec24450f-f60a-49fb-a9c1-d4dda8b4055f)

**Comment by mcorner** [comment]
1) At least on your HONOR 70 device you are sending traffic through Charles Proxy and having an SSL error.  I am not sure what you are trying to do there, but probably not going to work.  Please retry this with a non-proxied device.

2) Please try the example app on your device.  I think there is something wrong with this particular device, but we have to narrow it down.

3) You should also try the regular SDK (https://cloud.google.com/recaptcha-enterprise/docs/instrument-android-apps) in a sample app on that device to see if that works for you.

**Comment by 865102930** [comment]
> 1. At least on your HONOR 70 device you are sending traffic through Charles Proxy and having an SSL error.  I am not sure what you are trying to do there, but probably not going to work.  Please retry this with a non-proxied device.
> 2. Please try the example app on your device.  I think there is something wrong with this particular device, but we have to narrow it down.
> 3. You should also try the regular SDK (https://cloud.google.com/recaptcha-enterprise/docs/instrument-android-apps) in a sample app on that device to see if that works for you.

```
V/AudioManager(24736): querySoundEffectsEnabled...
I/SysUtils(24736): hw theme is enabled(false)
I/SysUtils(24736): build factory is HONOR
I/SysUtils(24736): the package isBuildAtLeastMagic6:true
W/SysUtils(24736): Exception--NullPointerException
I/SysUtils(24736): honor theme is enabled(false)
I/AwSettings(24736): selectHandleChangeEnbled(false)
I/hwbr_engine_a(24736): connectionTypeChanged connectionType = 2, connectionSubType = 0
I/SysUtils(24736): build factory is HONOR
I/SysUtils(24736): the package isBuildAtLeastMagic6:true
I/AwSettings(24736): getAdBlockEnabled:false
W/GooglePlayServicesUtil(24736): com.arnia.whk requires the Google Play Store, but it is missing.
I/hwschromium-4598(24736): [INFO:render_frame_host_manager.cc(2080)] HWBFCACHE: should_swap_result = 1
I/hwschromium-4598(24736): [INFO:render_frame_host_manager.cc(1035)] HWBFCACHE: GetSiteInstanceForNavigationRequest reason=DetermineSiteInstanceForURL => current_instance_impl
I/AwSettings(24736): getAdBlockEnabled:false
I/hwbr_engine_a(24736): connectionTypeChanged connectionType = 2, connectionSubType = 0
I/hwbr_engine_ChildProcLauncher(24736): on connect callback, pid=25025
I/hwschromium-4598(24736): [INFO:render_frame_host_manager.cc(2080)] HWBFCACHE: should_swap_result = 1
I/hwschromium-4598(24736): [INFO:render_frame_host_manager.cc(1035)] HWBFCACHE: GetSiteInstanceForNavigationRequest reason=DetermineSiteInstanceForURL => current_instance_impl
I/hwschromium-4598(24736): [INFO:adaptive_relayout_impl.cc(27)] enter ShouldDoAdaptiveRelayout
I/hwschromium-4598(24736): [INFO:adaptive_relayout_impl.cc(37)] exit ShouldDoAdaptiveRelayout, should[0]
W/hwschromium-4598(24736): [WARNING:browser_context.cc(611)] CloudControl BrowserContext::GetControlConfigByUrl cloud control config is empty or unenable
I/flutter (24736): Caught Platform exception on init: code:FL_INIT_FAILED-----msg:com.google.android.recaptcha.RecaptchaException: Key type invalid
I/hwschromium-4598(24736): [INFO:network_service_network_delegate.cc(161)] INFO: resource : https//*** error code: 404

```

**Comment by mcorner** [comment]
Ok, this problem is probably that you have to enable the option in your site key for use on "off play" applications (devices without the Play Store and GMSCore which are frequently found in China).  I have adjusted the title of the error report and will improve our docs here: 
https://cloud.google.com/recaptcha-enterprise/docs/reference/android/com/google/android/recaptcha/RecaptchaErrorCode#INVALID_KEYTYPE

There are a lot of different things in this issue, so I am going to close it, but please open a new issue with a specific issue if there is another one.
